set hdsFileList [list]
set ipFileList [list]
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/busdef_pkg.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/busdef_pkg_body.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/S00_AXI.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/register_array_resetval_rtl.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/axi_xfer_ctrl_fsm.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/cnt_modulus_c_rtl.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/fifo_distram_rtl.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/cnt_modulus_rtl.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/fifo_stream_ctrl_fsm.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/axi_master_control_struct.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/m00_axi_implementation.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/sbus_mux3_rtl.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/profiler_rtl.vhd"
lappend hdsFileList axi_dma_bridge
lappend hdsFileList "$::env(HDS_PROJECT_DIR)/axi_dma_bridge/hdl/top_axi_dma_bridge_struct.vhd"
set vlogGlobalFileList [list]

