onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top/U_0/dma_rd
add wave -noupdate /tb_top/U_0/dma_rd_addr
add wave -noupdate /tb_top/U_0/dma_rd_fifosize
add wave -noupdate /tb_top/U_0/dma_rd_mode
add wave -noupdate /tb_top/U_0/dma_rd_request_size
add wave -noupdate /tb_top/U_0/dma_rdata
add wave -noupdate /tb_top/U_0/dma_wdata
add wave -noupdate /tb_top/U_0/dma_wr
add wave -noupdate /tb_top/U_0/dma_wr_addr
add wave -noupdate /tb_top/U_0/dma_wr_fifosize
add wave -noupdate /tb_top/U_0/dma_wr_mode
add wave -noupdate /tb_top/U_0/dma_wr_request_size
add wave -noupdate /tb_top/U_0/sbus_ack
add wave -noupdate /tb_top/U_0/sbus_addr
add wave -noupdate /tb_top/U_0/sbus_be
add wave -noupdate /tb_top/U_0/sbus_rd
add wave -noupdate /tb_top/U_0/sbus_rdata
add wave -noupdate /tb_top/U_0/sbus_wdata
add wave -noupdate /tb_top/U_0/sbus_we
add wave -noupdate /tb_top/M00_AXI_ARADDR
add wave -noupdate /tb_top/M00_AXI_ARBURST
add wave -noupdate /tb_top/M00_AXI_ARCACHE
add wave -noupdate /tb_top/M00_AXI_ARID
add wave -noupdate /tb_top/M00_AXI_ARLEN
add wave -noupdate /tb_top/M00_AXI_ARLOCK
add wave -noupdate /tb_top/M00_AXI_ARPROT
add wave -noupdate /tb_top/M00_AXI_ARQOS
add wave -noupdate /tb_top/M00_AXI_ARREADY
add wave -noupdate /tb_top/M00_AXI_ARSIZE
add wave -noupdate /tb_top/M00_AXI_ARUSER
add wave -noupdate /tb_top/M00_AXI_ARVALID
add wave -noupdate /tb_top/M00_AXI_AWADDR
add wave -noupdate /tb_top/M00_AXI_AWBURST
add wave -noupdate /tb_top/M00_AXI_AWCACHE
add wave -noupdate /tb_top/M00_AXI_AWID
add wave -noupdate /tb_top/M00_AXI_AWLEN
add wave -noupdate /tb_top/M00_AXI_AWLOCK
add wave -noupdate /tb_top/M00_AXI_AWPROT
add wave -noupdate /tb_top/M00_AXI_AWQOS
add wave -noupdate /tb_top/M00_AXI_AWREADY
add wave -noupdate /tb_top/M00_AXI_AWSIZE
add wave -noupdate /tb_top/M00_AXI_AWUSER
add wave -noupdate /tb_top/M00_AXI_AWVALID
add wave -noupdate /tb_top/M00_AXI_BID
add wave -noupdate /tb_top/M00_AXI_BREADY
add wave -noupdate /tb_top/M00_AXI_BRESP
add wave -noupdate /tb_top/M00_AXI_BUSER
add wave -noupdate /tb_top/M00_AXI_BVALID
add wave -noupdate /tb_top/M00_AXI_RDATA
add wave -noupdate /tb_top/M00_AXI_RID
add wave -noupdate /tb_top/M00_AXI_RLAST
add wave -noupdate /tb_top/M00_AXI_RREADY
add wave -noupdate /tb_top/M00_AXI_RRESP
add wave -noupdate /tb_top/M00_AXI_RUSER
add wave -noupdate /tb_top/M00_AXI_RVALID
add wave -noupdate /tb_top/M00_AXI_WDATA
add wave -noupdate /tb_top/M00_AXI_WLAST
add wave -noupdate /tb_top/M00_AXI_WREADY
add wave -noupdate /tb_top/M00_AXI_WSTRB
add wave -noupdate /tb_top/M00_AXI_WUSER
add wave -noupdate /tb_top/M00_AXI_WVALID
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_done
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_enable
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_fifo_rd_ptr
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_fifo_wr_ptr
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_init
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_loopback
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_mode
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_num_reset
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_rd_base_address
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_rd_continuous
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_rd_fifo_size
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_rd_init
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_rd_reset
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_rd_snapshot
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_read
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_wr_base_address
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_wr_continuous
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_wr_fifo_size
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_wr_init
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_wr_reset
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_wr_snapshot
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_write
add wave -noupdate /tb_top/U_0/U_0/i_topcon/dma_rd
add wave -noupdate /tb_top/U_0/U_0/i_topcon/dma_rd_enable
add wave -noupdate /tb_top/U_0/U_0/i_topcon/dma_wr_enable
add wave -noupdate /tb_top/U_0/U_0/i_topcon/rd_threshold
add wave -noupdate /tb_top/U_0/U_0/i_topcon/wr_threshold
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_done
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_rd_en
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_rd_init
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_wr_en
add wave -noupdate /tb_top/U_0/U_0/i_topcon/xfer_wr_init
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {531908 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1050 us}
