-- VHDL Entity training_solutions_lib.tb_chapter1.symbol
--
-- Created:
--          by - net.UNKNOWN (KPERSM7467)
--          at - 13:08:06 19.10.2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity tb_chapter1 is
-- Declarations

end tb_chapter1 ;

--
-- VHDL Architecture training_solutions_lib.tb_chapter1.struct
--
-- Created:
--          by - net.UNKNOWN (KPERSM7467)
--          at - 08:25:20 25.10.2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library training_solutions_lib;

architecture struct of tb_chapter1 is

   -- Architecture declarations

   -- Internal signal declarations
   signal buttons  : std_logic_vector(3 downto 0);
   signal clk      : std_logic;
   signal encoder0 : std_logic_vector(1 downto 0);
   signal encoder1 : std_logic_vector(1 downto 0);
   signal leds     : std_logic_vector(3 downto 0);
   signal leds1    : std_logic_vector(3 downto 0);
   signal leds2    : std_logic_vector(3 downto 0);
   signal leds3    : std_logic_vector(3 downto 0);
   signal leds_2f  : std_logic_vector(3 downto 0);
   signal sliders  : std_logic_vector(3 downto 0);


   -- Component Declarations
   component bhv_zybo_tester1
   generic (
      commands_g   : string := "commands.txt";
      clk_period_g : time   := 8 ns
   );
   port (
      buttons  : out    std_logic_vector (3 downto 0);
      clk      : out    std_logic ;
      encoder0 : out    std_logic_vector (1 downto 0);
      encoder1 : out    std_logic_vector (1 downto 0);
      sliders  : out    std_logic_vector (3 downto 0)
   );
   end component;
   component circuit_ch1_1a
   port (
      buttons  : in     std_logic_vector (3 downto 0);
      clk      : in     std_logic;
      encoder0 : in     std_logic_vector (1 downto 0);
      encoder1 : in     std_logic_vector (1 downto 0);
      sliders  : in     std_logic_vector (3 downto 0);
      buzzer   : out    std_logic_vector (1 downto 0);
      leds     : out    std_logic_vector (3 downto 0)
   );
   end component;
   component circuit_ch1_1b
   port (
      buttons  : in     std_logic_vector (3 downto 0);
      clk      : in     std_logic;
      encoder0 : in     std_logic_vector (1 downto 0);
      encoder1 : in     std_logic_vector (1 downto 0);
      sliders  : in     std_logic_vector (3 downto 0);
      buzzer   : out    std_logic_vector (1 downto 0);
      leds     : out    std_logic_vector (3 downto 0)
   );
   end component;
   component circuit_ch1_1c
   port (
      buttons  : in     std_logic_vector (3 downto 0);
      clk      : in     std_logic;
      encoder0 : in     std_logic_vector (1 downto 0);
      encoder1 : in     std_logic_vector (1 downto 0);
      sliders  : in     std_logic_vector (3 downto 0);
      buzzer   : out    std_logic_vector (1 downto 0);
      leds     : out    std_logic_vector (3 downto 0)
   );
   end component;
   component circuit_ch1_1d
   port (
      buttons  : in     std_logic_vector (3 downto 0);
      clk      : in     std_logic;
      encoder0 : in     std_logic_vector (1 downto 0);
      encoder1 : in     std_logic_vector (1 downto 0);
      sliders  : in     std_logic_vector (3 downto 0);
      buzzer   : out    std_logic_vector (1 downto 0);
      leds     : out    std_logic_vector (3 downto 0)
   );
   end component;
   component circuit_ch1_2f
   port (
      buttons  : in     std_logic_vector (3 downto 0);
      clk      : in     std_logic;
      encoder0 : in     std_logic_vector (1 downto 0);
      encoder1 : in     std_logic_vector (1 downto 0);
      sliders  : in     std_logic_vector (3 downto 0);
      buzzer   : out    std_logic_vector (1 downto 0);
      leds     : out    std_logic_vector (3 downto 0)
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : bhv_zybo_tester1 use entity training_solutions_lib.bhv_zybo_tester1;
   for all : circuit_ch1_1a use entity training_solutions_lib.circuit_ch1_1a;
   for all : circuit_ch1_1b use entity training_solutions_lib.circuit_ch1_1b;
   for all : circuit_ch1_1c use entity training_solutions_lib.circuit_ch1_1c;
   for all : circuit_ch1_1d use entity training_solutions_lib.circuit_ch1_1d;
   for all : circuit_ch1_2f use entity training_solutions_lib.circuit_ch1_2f;
   -- pragma synthesis_on


begin

   -- Instance port mappings.
   U_4 : bhv_zybo_tester1
      generic map (
         commands_g   => "commands.txt",
         clk_period_g => 8 ns
      )
      port map (
         buttons  => buttons,
         clk      => clk,
         encoder0 => encoder0,
         encoder1 => encoder1,
         sliders  => sliders
      );
   U_0 : circuit_ch1_1a
      port map (
         buttons  => buttons,
         sliders  => sliders,
         encoder0 => encoder0,
         encoder1 => encoder1,
         clk      => clk,
         buzzer   => open,
         leds     => leds
      );
   U_1 : circuit_ch1_1b
      port map (
         buttons  => buttons,
         sliders  => sliders,
         encoder0 => encoder0,
         encoder1 => encoder1,
         clk      => clk,
         buzzer   => open,
         leds     => leds1
      );
   U_2 : circuit_ch1_1c
      port map (
         buttons  => buttons,
         sliders  => sliders,
         encoder0 => encoder0,
         encoder1 => encoder1,
         clk      => clk,
         buzzer   => open,
         leds     => leds2
      );
   U_3 : circuit_ch1_1d
      port map (
         buttons  => buttons,
         sliders  => sliders,
         encoder0 => encoder0,
         encoder1 => encoder1,
         clk      => clk,
         buzzer   => open,
         leds     => leds3
      );
   U_5 : circuit_ch1_2f
      port map (
         buttons  => buttons,
         sliders  => sliders,
         encoder0 => encoder0,
         encoder1 => encoder1,
         clk      => clk,
         buzzer   => open,
         leds     => leds_2f
      );

end struct;
