-- VHDL Entity training_lib.tb_chapter2.symbol
--
-- Created:
--          by - net.UNKNOWN (KPERSM7467)
--          at - 19:49:03 19.10.2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity tb_chapter2 is
-- Declarations

end tb_chapter2 ;

--
-- VHDL Architecture training_lib.tb_chapter2.struct
--
-- Created:
--          by - net.UNKNOWN (KPERSM7467)
--          at - 20:16:50 19.10.2017
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library training_lib;

architecture struct of tb_chapter2 is

   -- Architecture declarations

   -- Internal signal declarations
   signal buttons  : std_logic_vector(3 downto 0);
   signal clk      : std_logic;
   signal encoder0 : std_logic_vector(1 downto 0);
   signal encoder1 : std_logic_vector(1 downto 0);
   signal leds_2a  : std_logic_vector(3 downto 0);
   signal sliders  : std_logic_vector(3 downto 0);


   -- Component Declarations
   component bhv_zybo_tester1
   generic (
      commands_g   : string := "commands.txt";
      clk_period_g : time   := 8 ns
   );
   port (
      buttons  : out    std_logic_vector (3 downto 0);
      clk      : out    std_logic ;
      encoder0 : out    std_logic_vector (1 downto 0);
      encoder1 : out    std_logic_vector (1 downto 0);
      sliders  : out    std_logic_vector (3 downto 0)
   );
   end component;
   component circuit_ch2_1a
   port (
      buttons  : in     std_logic_vector (3 downto 0);
      clk      : in     std_logic;
      encoder0 : in     std_logic_vector (1 downto 0);
      encoder1 : in     std_logic_vector (1 downto 0);
      sliders  : in     std_logic_vector (3 downto 0);
      buzzer   : out    std_logic_vector (1 downto 0);
      leds     : out    std_logic_vector (3 downto 0)
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : bhv_zybo_tester1 use entity training_lib.bhv_zybo_tester1;
   for all : circuit_ch2_1a use entity training_lib.circuit_ch2_1a;
   -- pragma synthesis_on


begin

   -- Instance port mappings.
   U_0 : bhv_zybo_tester1
      generic map (
         commands_g   => "commands_2.txt",
         clk_period_g => 8 ns
      )
      port map (
         buttons  => buttons,
         clk      => clk,
         encoder0 => encoder0,
         encoder1 => encoder1,
         sliders  => sliders
      );
   U_1 : circuit_ch2_1a
      port map (
         buttons  => buttons,
         sliders  => sliders,
         encoder0 => encoder0,
         encoder1 => encoder1,
         clk      => clk,
         buzzer   => open,
         leds     => leds_2a
      );

end struct;
